### PR TITLE
Update the README.md

### PR DESCRIPTION
**Pull request by pbw-Kevin**

### CODE REVIEW

**Comment by pbw-Kevin** [comment]
And the parameters `clear` and `verbose` in official docs become invalid. Should those be updated?

**Comment by stevenjoezhang** [comment]
`clear` and `verbose` are still used:
https://github.com/hexojs/hexo-deployer-ftpsync/blob/3ef51bedf2e54c82782de2544bc0aeb05e0cdc57/lib/deployer.js#L42
https://github.com/hexojs/hexo-deployer-ftpsync/blob/3ef51bedf2e54c82782de2544bc0aeb05e0cdc57/lib/deployer.js#L30

If these options are not working as expected, it could mean there is a bug.

**Comment by stevenjoezhang** [comment]
You can modify the documentation to say: 
```
If `clear` is set to true, this plugin will delete files and directories on the remote server to match the local machine. Use this plugin in production at your own risk.
```

**Comment by pbw-Kevin** [comment]
Well, it seems that it's my fault.
After reinstall all the dependencies, every thing works well.
README.md has changed. Sorry for my rudeness.

**Pull request merged**
