### PR TITLE
refactor: switch to basic-ftp

### PR DESCRIPTION
**Pull request by stevenjoezhang**
There are usability issues with this plugin (it depends on a library that hasn't been updated for many years).

### CODE REVIEW

**Review by SukkaW — APPROVED** [review]
LGTM!

**Comment by pbw-Kevin** [comment]
Sounds great. But when to update npm ver?

**Comment by stevenjoezhang** [comment]
@yoshinorin Can you help publish the new version (0.2.0) on npm? (version in `package.json` already updated in this pull request). Thanks!

**Comment by yoshinorin** [comment]
@pbw-Kevin @stevenjoezhang 
Just now I published a new version (`v0.2.0`)

https://www.npmjs.com/package/hexo-deployer-ftpsync/v/0.2.0

Thank you :)

**Comment by pbw-Kevin** [comment]
Thank u so much:)))

**Comment by pbw-Kevin** [comment]
Thank u so much:)))
It worried me a long time:()

**Pull request merged**
